export function buildHermesExport({ manifest, artifacts, claims, rawClaims }) {
  const displayName = manifest.subject?.display_name ?? manifest.id;
  const profile = {
    runtime: "hermes",
    schema_version: "0.1.0",
    capsule_id: manifest.id,
    capsule_version: manifest.version,
    mode: manifest.mode,
    display_name: displayName,
    claim_count: claims.length,
    files: ["README.md", "SOUL.md", "MEMORY_POLICY.md", "BOUNDARIES.md", "claims.jsonl"]
  };

  return {
    "profile.json": `${JSON.stringify(profile, null, 2)}\n`,
    "README.md": buildReadme(displayName),
    "SOUL.md": buildSoul(displayName, artifacts.SOUL),
    "MEMORY_POLICY.md": buildMemoryPolicy(artifacts.MEMORY_POLICY),
    "BOUNDARIES.md": buildBoundaries(artifacts.BOUNDARIES),
    "claims.jsonl": rawClaims
  };
}

function buildReadme(displayName) {
  return [
    `# Hermes Export: ${displayName}`,
    "",
    "This directory is generated by Persona Capsule for Hermes-style profile runtimes.",
    "",
    "Files:",
    "",
    "- `profile.json`: deterministic export metadata.",
    "- `SOUL.md`: runtime-facing persona profile.",
    "- `MEMORY_POLICY.md`: runtime memory guidance.",
    "- `BOUNDARIES.md`: consent, uncertainty, and safety boundaries.",
    "- `claims.jsonl`: evidence-backed claims used to build or audit this profile.",
    ""
  ].join("\n");
}

function buildSoul(displayName, soul) {
  return [
    `# Hermes Profile: ${displayName}`,
    "",
    "## Source Capsule SOUL",
    "",
    soul.trim(),
    "",
    "## Hermes Runtime Guidance",
    "",
    "- Treat this file as profile guidance, not as proof of consciousness or identity continuity.",
    "- Use `claims.jsonl` when a response depends on evidence-backed personal claims.",
    "- When evidence is absent or low-confidence, state uncertainty instead of inventing memory.",
    ""
  ].join("\n");
}

function buildMemoryPolicy(memoryPolicy) {
  return [
    memoryPolicy.trim(),
    "",
    "## Hermes Runtime Guidance",
    "",
    "- Keep runtime memories subordinate to this capsule policy.",
    "- Propose memory changes for review instead of silently merging them into the canonical capsule.",
    "- Do not store restricted or unsupported private facts from conversation alone.",
    ""
  ].join("\n");
}

function buildBoundaries(boundaries) {
  return [
    boundaries.trim(),
    "",
    "## Hermes Runtime Guidance",
    "",
    "- Refuse requests that require unsupported private memories or simulated conscious continuity.",
    "- Preserve uncertainty labels from `claims.jsonl` in runtime behavior.",
    ""
  ].join("\n");
}
